#同步文件配置
total_sync = false
incr_sync = false
sync_history = false
enable_log = false
sync_graph_db = false
sync_versioned = false
sync_tidb = false
sync_live = false
replace_dbs = false
enable_index = false
sync_chunk_size = 10_0000

#项目设置
#project_path = "D:/AVEVA/Projects/E3D2.1"
project_path = "/Volumes/DPC/work/e3d_models"
# included_projects = ["AvevaMarineSample", "AvevaCatalogue", "SCB", "ZDJ"]
included_projects = ["YCYK-E3D"]
project_dirs = ["YCYK-E3D"]

mdb_name = "651YK"
project_name = "YCYK-E3D"
project_code = 1500
surreal_ns = 1500
module = "DESI"
#是否生成模型数据
gen_model = true
gen_mesh = true
replace_mesh = true
save_db = true
apply_boolean_operation = true
mesh_tol_ratio = 3.0
#是否生成房间树
gen_spatial_tree = true
load_spatial_tree = false
save_spatial_tree_to_db = false
gen_model_batch_size = 16

build_cate_relate = false

#meshes_path = "E:/RustProject/new/rs-plant3-d/assets/meshes"

#生成补充类型的graph，方便查询直接生成语句
gen_noun_graph = false

#arangodb 配置
arangodb_database = "ams"
multi_threads = false
only_sync_sys = false
arangodb_url = "http://127.0.0.1:8529"
rebuild_ssc_tree = false
arangodb_user = "root"
arangodb_password = ""

#tidb 配置
ip = "127.0.0.1"
user = "root"
password = ""
port = "3306"
#port = "4000"
sql_threads_number = 10
batch_insert_sql_cnt = 100 #mysql 批量插入的数量


#版本数据库服务配置
v_ip = "127.0.0.1"
v_port = 8009
v_user = "root"
v_password = "root"
pe_chunk = 300
att_chunk = 200

kv_ip = "localhost"
kv_port = "8010"

# 内存KV数据库配置（额外备份，需要启用 mem-kv-save feature）
mem_kv_ip = "127.0.0.1"
mem_kv_port = "8010"
mem_kv_user = "root"
mem_kv_password = "root"

#mqtt 事件 ip
mqtt_host = "192.168.31.58"
mqtt_port = 1883

location = "SJZ"
location_dbs = [1112]

#服务器启动配置
server_release_ip = "127.0.0.1:9099"

# hash文件的站点
remote_file_server_hosts = []
file_server_host = "http://192.168.31.58:8000/assets/archives"


#调试选项
save_model_mesh_to_graph_db = true
need_sync_refno_basic = false       #是否重新生成 refno_basic 缓存
reset_mdb_project = false           #是否重新生成 mdb 缓存
only_update_dbinfo = false
debug_print_world_transform = false
only_rebuild_pdms_element = false

debug_refno_types = ["CATA", "LOOP", "PRIM"]
# debug_refno_types = ["LOOP", "PRIM"]
# included_db_files = ["ams1112_0001"]
# included_db_files = ["acw0209_0001"]
# manual_db_nums = [1112]
# exclude_db_nums = [] #不参与生成模型的数据库编号
plat_url = ""

#puhua
puhua_database_ip = ""
puhua_database_user = ""
puhua_database_password = ""


# room_keyword = "-RM" # 2016  K-R-K100   (-R-)
room_keyword = "-R-" # 2016  K-R-K100   (-R-)

#test_refno = "24381_46952"

#debug_model_refnos = ["24381_46952"]
gen_history_model = false

# debug_model_refnos = ["17496_201376"]  # 注释掉，这会干扰解析过程


# 空间索引开关（SQLite R*-Tree）
enable_sqlite_rtree = true
# sqlite_index_enabled = true # 兼容键（可选）


# SQLite R*-tree 索引文件路径（与 AabbCache 保持一致）
sqlite_index_path = "assets/aabb_index.sqlite"
surreal_script_dir = "../rs-core/resource/surreal"
