[net]
git-fetch-with-cli = true

# [target.x86_64-pc-windows-msvc]
# linker = "rust-lld.exe"
# rustdocflags = ["-Clinker=rust-lld.exe"]

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "cranelift"

# [build]
# rustflags = ["-Z", "threads=8"]

# WASM 目标特定配置
[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+bulk-memory",
    "--cfg=web_sys_unstable_apis",
    "--cfg=getrandom_backend=\"wasm_js\""
]

#[target.x86_64-unknown-linux-musl]
#linker = "x86_64-linux-musl-gcc"
#[target.x86_64-pc-windows-gnu]
#linker = "x86_64-w64-mingw32-gcc"
#[target.x86_64-unknown-linux-musl]
#linker = "rust-lld"
